config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create, :destroy, :edit] do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: [:ingredient] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :description, presence: true
  validates :rating, inclusion: { in: 0..5 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :image)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:destroy]
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    #does belongs to a cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @review = Review.new
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end


  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @dose = Dose.new
      render 'cocktails/show'
    end
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
     @review = Review.new(review_params)
  end
  private

  def review_params
    params.require(:review).permit(:rating, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/cocktails/edit.html.erb
<div class = "cocktail-edit-container" style = "margin-top: 16%">

<div class="container">
  <div class="table">
    <div class="glassHead">
      <div class="strawContainer">
        <div class="straw">
        </div>
        <div class="lemon">
        </div>
        <div class="ice">
        </div>
        <div class="ice ice2">
        </div>
        <div class="ice ice3">
        </div>
      </div>
    </div>
    <div class="liquid2">
    </div>
    <div class="liquid">
    </div>
    <div class="glassBar">
    </div>
    <div class="glassFoot">
    </div>
  </div>

</div>





<div class="form-page pt-3">
  <div class="form-div container pt-3">
    <h1>Edit Cocktail</h1>

    <%= simple_form_for(@cocktail) do |f| %>

      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :photo %>
      </div>

      <div class="form-actions">
        <%= f.submit class: 'btn-new'  %>

      </div>
    <% end %>
  </div>
</div>
</div>

app/views/cocktails/index.html.erb
<html>

<head>
  <link rel="stylesheet" href="tiles.scss">
</head>
<body>


<header>
      <div class="navbar">
        <ul class="nav">
          <li class="item">
            <a href=> <%= link_to "Home", root_path  %></a>
          </li>


          <li class="item">
            <a href=><%= link_to "Add a new cocktail",  new_cocktail_path%></a>
          </li>

         <li class="item" style = "width:20px;">
         <i class="fas fa-cocktail"></i>
        </li>

         <li class="item" style="font-family: fantasy;">
            <p>Best Bar in London</p>
          </li>
        </ul>


      </div>
    </header>


<div id="loader" style="margin-top: 1%; position: absolute;">
    <div id="lemon"></div>
    <div id="straw"></div>
    <div id="glass">
        <div id="cubes">
            <div></div>
            <div></div>
            <div></div>
        </div>
        <div id="drink"></div>
        <span id="counter"></span>
    </div>
    <div id="coaster"></div>

<div><b>Please wait while<br>we fill up your glass...</b></div>
</div>






<div class = "cocktails-container" style = "margin-top: 65%">
<% @cocktails.each do |cocktail| %>

<div class="cards" style = " margin-top: 6%;">


  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/1418358/pexels-photo-1418358.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)">
     <%= link_to  cocktail.name, cocktail_path(cocktail)%>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/302515/pexels-photo-302515.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)">
     <%= link_to cocktail.name, cocktail_path(cocktail) %>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/605408/pexels-photo-605408.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)">
     <%= link_to cocktail.name, cocktail_path(cocktail) %>
  </div>


</div>

<% end %>
</div>














</body>
</html>

app/views/cocktails/new.html.erb
<div class = "new-cocktail-container" style = "display: flex; margin-top: 49px;">
<div id="loading">
  <svg xmlns="http://www.w3.org/2000/svg" id="rocksGlass" viewBox="-8.233 -8.233 122.466 122.466" height="300px">
    <path d=" M 12.556 103 L 3 3 L 103 3 L 93.347 103 L 12.556 103 L 12.556 103 Z " fill="rgb(255,255,255)" vector-effect="non-scaling-stroke" stroke-width="5.616" stroke="rgb(70,70,70)" stroke-linejoin="miter" stroke-linecap="butt" stroke-miterlimit="4"/>
    <g opacity="0.8">
      <path d=" M 12.251 56.089 L 93.751 56.089 L 88.851 98.111 L 17.351 98.111 L 12.251 56.089 Z " fill="rgb(147,72,3)"/>
    </g>
    <g id="iceLeft" style="opacity:0.6;">
      <path d=" M 46.751 81.733 L 27.662 84.671 L 16.662 65.618 L 35.751 62.68 L 46.751 81.733 Z " fill="rgb(187,222,251)"/>
      <path d=" M 46.751 81.733 L 58.839 66.671 L 47.839 47.618 L 35.751 62.68 L 46.751 81.733 Z " fill="rgb(33,150,243)"/>
      <path d=" M 16.662 65.618 L 28.751 50.556 L 47.839 47.618 L 35.751 62.68 L 16.662 65.618 Z " fill="rgb(144,202,249)"/>
    </g>
    <g id="iceRight" style="opacity:0.6;">
      <path d=" M 61.218 92.7 L 45.643 81.28 L 51.337 60.03 L 66.912 71.45 L 61.218 92.7 Z " fill="rgb(187,222,251)"/>
      <path d=" M 61.218 92.7 L 80.416 90.598 L 86.11 69.347 L 66.912 71.45 L 61.218 92.7 Z " fill="rgb(33,150,243)"/>
      <path d=" M 51.337 60.03 L 70.535 57.927 L 86.11 69.347 L 66.912 71.45 L 51.337 60.03 Z " fill="rgb(144,202,249)"/>
    </g>

  </svg>

</div>



<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Create a new cocktail</h1>
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: 'btn-new'  %>
      <% end %>
    </div>
  </div>
</div>

</div>

app/views/cocktails/show.html.erb
<div class = "container-cocktail-show" style = "display: flex; margin-bottom: 100px;">
<div class = "picture" style = "margin-top: 20px;">
<div class="wrapper">
 <div class="cocktail">
   <div class="liquid"></div>
   <div class="ice-cubes">
     <div class="ice-cube ice-cube-1"></div>
     <div class="ice-cube ice-cube-2"></div>
     <div class="ice-cube ice-cube-3"></div>
   </div>
   <div class="lemon-slice"></div>
   <div class="leaves">
     <div class="leave leave-1"></div>
     <div class="leave leave-2"></div>
     <div class="leave leave-3"></div>
   </div>
   <div class="straw"></div>
   <div class="straw-surface"></div>
   <div class="shadow"></div>
  </div>
</div>
</div>



<div class = container-cocktail-review>
<div class="container ">
  <div class="row">
    <div class="col-xs-12" style = "margin-left: 31%;">
      <h1> <%= @cocktail.name %></h1>
      <%= cl_image_tag @cocktail.photo, height: 250, width: 350, crop: :fill %>
      <div class = "btn" style = "display: block; margin-top: 110%;">

      <div class = "btn-new"> <%= link_to "Back to all cocktails", root_path %></div>
      <div class = "btn-new"> <%= link_to 'Delete cocktail', cocktail_path(@cocktail),  method: :delete, data: { confirm: "Are you sure?" }%></div>
      <div class = "btn-new"> <%= link_to 'Edit cocktail', edit_cocktail_path(@cocktail), method: :get%> </div>

    </div>
   </div>
  </div>
  </div>
 </div>

</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>ADD a new DOSE</h1>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient, collection: Ingredient.all %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render 'shared/navbar' %>

    <%= yield %>
     <%= javascript_include_tag "application" %>
       <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
<%= render 'shared/footer'%>
  </body>
</html>

app/views/reviews/new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [@cocktail, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container-footer">
    <div class="nine columns">
      <p>Created with love by Gina.</p>
    </div>
    <div class="three columns"> <span class="typcn typcn-social-facebook-circular socialIcons"></span> <span class="typcn typcn-social-instagram-circular socialIcons"></span> <span class="typcn typcn-social-google-plus-circular socialIcons"></span> <span class="typcn typcn-social-linkedin-circular socialIcons"></span> </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header>
      <div class="navbar">
        <ul class="nav">
          <li class="item">
            <a href=> <%= link_to "Home", root_path  %></a>
          </li>

          <li class="item">
            <a href=><%= link_to "Add a new cocktail",  new_cocktail_path%></a>
          </li>

         <li class="item" style = "width:25px;">
         <i class="fas fa-cocktail"></i>
        </li>
        </ul>


      </div>
    </header>